### ISSUE TITLE
Logo offer for One Shoot

### ISSUE THREAD

**Issue by familqasimov** [SmashKs/OneShoot#14]
Hi sir. I'm graphics designer. I have studied your work. I think a new logo will make you more visible. I would like to offer logo. I can give you all the formats of the design free.

Best regard
Famil

**Comment by pokk** [comment]
Hi Famil,

Thank you for following my works.
Im really glad to know you'd like to help us to open our visible. You could email to my email and we might be able to discuss it!

Also, we don't have a graphics designer for designing our application or logos, if you're interested in, we might be able to create some awesome app.

Best regard,
Jieyi

**Comment by familqasimov** [comment]
Thank you firstly for accepting the offer. I offer you 4 forms. If you have another form of mind, say your suggestion.

![oneshoot](https://user-images.githubusercontent.com/36432269/40880203-8be8f438-66bd-11e8-99e8-4ed5e8463911.png)

best regard
Famil

**Comment by pokk** [comment]
Hi Famil,

Thank you very much. We like your design very much.
About the last logo, we really like reflection(white circle) on the camera lens. How do you think it?

Jieyi

**Comment by familqasimov** [comment]
Fine
I think it looks better.

![oneshoot2](https://user-images.githubusercontent.com/36432269/40940807-017d21ea-685a-11e8-8c09-86c0d7b35abf.png)

Can I send a PR if you like it?

Famil

**Comment by pokk** [comment]
Hi Famil,

Sure, we welcome a PR very much. This is pretty good, I like it very much!

Jieyi

**Comment by familqasimov** [comment]
Hi friend. Please hire source all editable and png formats with sizes. Thank you for merged logo.

https://drive.google.com/drive/u/1/folders/1wZYBO3SO-vKkfj-rCRNSP6Qk7JAKoKyh

**Comment by pokk** [comment]
@familqasimov 

Thank you very much! I'll keep it and close this issue.
